name: Test POSIX compliance

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: devscripts shellcheck
        version: 1.0

    - name: Run test_posix_compliance.sh
      run: |
        chmod +x ./testers/test_posix_compliance.sh
        ./testers/test_posix_compliance.sh

